// backend/src/shared/constants.js

const CATEGORIES = Object.freeze(['HEALTH', 'FINANCE', 'PERSONAL_DEV', 'RELATIONSHIPS', 'CAREER', 'OTHER']);
const ALLOWED_CATEGORIES = CATEGORIES;

const STATUSES = Object.freeze(['PENDING', 'IN_PROGRESS', 'COMPLETED', 'ARCHIVED', 'FAILED']);
const ALLOWED_STATUSES = STATUSES;

// previousStatus cannot be ARCHIVED
const PREVIOUS_STATUSES = Object.freeze(STATUSES.filter(s => s !== 'ARCHIVED'));

const STATUS_TRANSITIONS = Object.freeze({
    PENDING: ['IN_PROGRESS', 'ARCHIVED', 'FAILED'],
    IN_PROGRESS: ['COMPLETED', 'ARCHIVED', 'FAILED', 'PENDING'],
    COMPLETED: ['ARCHIVED', 'IN_PROGRESS'],
    ARCHIVED: ['PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED'],
    FAILED: ['PENDING', 'IN_PROGRESS', 'ARCHIVED'],
});

module.exports = { CATEGORIES, ALLOWED_CATEGORIES, STATUSES, ALLOWED_STATUSES, PREVIOUS_STATUSES, STATUS_TRANSITIONS };
